kind: pipeline
type: docker
name: default

steps:
- name: build_gentoo_environment
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t gentoo_environment .

- name: build
  image: gentoo_environment
  pull: if-not-exists
  commands:
  - cd build
  - rm -f CMakeCache.txt
  - cmake -Dbuild_tests=OFF ..
  - make timesheeting
  depends_on:
  - build_gentoo_environment

- name: test_environment
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t test_environment test/.
  depends_on:
  - build_gentoo_environment

- name: test_build
  image: test_environment
  pull: if-not-exists
  commands:
  - cd build
  - rm -f CMakeCache.txt
  - cmake -Dbuild_tests=ON ..
  - make timesheeting_tests
  depends_on:
  - test_environment

- name: test_run
  image: test_environment
  pull: if-not-exists
  commands:
  - ./build/timesheeting_tests
  depends_on:
  - test_build

- name: latex_environment
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t latex_environment doc/.

- name: PRJ1-SPE1
  image: latex_environment
  pull: if-not-exists
  commands:
  - cd doc/spec/
  - latexmk -pdf spec.tex
  depends_on:
  - latex_environment

- name: PRJ1-SAD1
  image: latex_environment
  pull: if-not-exists
  commands:
  - cd doc/sad/
  - latexmk -pdf sad.tex
  depends_on:
  - latex_environment

- name: PRJ1-IRS1
  image: latex_environment
  pull: if-not-exists
  commands:
  - cd doc/irs/
  - latexmk -pdf irs.tex
  depends_on:
  - latex_environment

- name: PRJ1-SRD1
  image: latex_environment
  pull: if-not-exists
  commands:
  - cd doc/srd/
  - latexmk -pdf srd.tex
  depends_on:
  - latex_environment

- name: PRJ1-TST1
  image: latex_environment
  pull: if-not-exists
  commands:
  - cd doc/tst/
  - latexmk -pdf tst.tex
  depends_on:
  - latex_environment

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
