kind: pipeline
type: docker
name: default

steps:
- name: build_gentoo_environment
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t gentoo_environment .

- name: build
  image: gentoo_environment
  pull: if-not-exists
  commands:
  - cd build
  - cmake ..
  - make timesheeting
  depends_on:
  - build_gentoo_environment

- name: latex_environment
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t latex_environment doc/.

- name: compile_documentation
  image: latex_environment
  pull: if-not-exists
  commands:
  - cd doc/spec/
  - latexmk -pdf spec.tex
  depends_on:
  - latex_environment

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
