kind: pipeline
type: docker
name: default

steps:
- name: build_gentoo_environment
  image: docker
  environment:
    DOCKER_USER:
      from_secret: DOCKER_USER
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
  - docker build -t gentoo_environment .

- name: build
  image: gentoo_environment
  pull: never
  commands:
  - rm -rf build/*
  - cd build
  - cmake ..
  - make timesheeting
  depends_on:
  - build_gentoo_environment

- name: test_environment
  image: docker
  environment:
    DOCKER_USER:
      from_secret: DOCKER_USER
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
  - docker build -t test_environment test/.
  depends_on:
  - build_gentoo_environment

- name: static_analysis
  image: test_environment
  pull: never
  failure: ignore
  commands:
  - rm -rf build_analysis
  - mkdir -p build_analysis
  - cd build_analysis
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - cd ..
  - cppcheck --project=build_analysis/compile_commands.json --check-level=exhaustive --enable=all --suppress=missingIncludeSystem --std=c++23 -itest/ --error-exitcode=1
  depends_on:
  - test_environment

- name: include_analysis
  image: test_environment
  pull: never
  failure: ignore
  commands:
  - rm -rf build_include_analysis
  - mkdir -p build_include_analysis
  - cd build_include_analysis
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - env-update
  - source /etc/profile
  - iwyu_tool.py -p . -- -Xiwyu --error -Xiwyu --no_fwd_decls
  depends_on:
  - test_environment

- name: test_build
  image: test_environment
  pull: never
  commands:
  - rm -rf build_test
  - mkdir -p build_test
  - cd build_test
  - cmake -Dbuild_tests=ON ..
  - make timesheeting_tests
  depends_on:
  - test_environment

- name: test_run
  image: test_environment
  pull: never
  failure: ignore
  commands:
  - ./build_test/timesheeting_tests
  depends_on:
  - test_build

- name: test_coverage
  image: test_environment
  pull: never
  failure: ignore
  commands:
  - rm -rf build_coverage
  - mkdir -p build_coverage
  - cd build_coverage
  - cmake -Dbuild_coverage=ON ..
  - make timesheeting_coverage_report
  depends_on:
  - test_run

- name: latex_environment
  image: docker
  failure: ignore
  environment:
    DOCKER_USER:
      from_secret: DOCKER_USER
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
  - docker build -t latex_environment doc/.

- name: build_doxygen
  image: latex_environment
  pull: never
  failure: ignore
  commands:
  - rm -rf build_doxygen
  - mkdir -p build_doxygen
  - doxygen Doxyfile
  depends_on:
  - latex_environment

- name: deploy_gh_pages
  image: latex_environment
  pull: never
  failure: ignore
  commands:
  - rm -rf gh_pages
  - git clone --depth 1 --branch gh-pages https://thomashoullier:$GITHUB_PAGES_TOKEN@github.com/thomashoullier/timesheeting.git gh_pages
  - rm -rf gh_pages/*
  - cp -r build_doxygen/html gh_pages/doxygen
  - cp -r build_coverage/timesheeting_coverage_report/ gh_pages/lcov
  - cd gh_pages
  - git add *
  - git commit -am "CI github pages deployment."
  - git push origin gh-pages
  environment:
    GITHUB_PAGES_TOKEN:
      from_secret: GITHUB_PAGES_TOKEN
  depends_on:
  - build_doxygen
  - test_coverage

- name: PRJ1-SPE1
  image: latex_environment
  pull: never
  failure: ignore
  commands:
  - cd doc/spec/
  - latexmk -pdf spec.tex
  depends_on:
  - latex_environment

- name: PRJ1-SAD1
  image: latex_environment
  pull: never
  failure: ignore
  commands:
  - cd doc/sad/
  - latexmk -pdf sad.tex
  depends_on:
  - latex_environment

- name: PRJ1-IRS1
  image: latex_environment
  pull: never
  failure: ignore
  commands:
  - cd doc/irs/
  - latexmk -pdf irs.tex
  depends_on:
  - latex_environment

- name: PRJ1-SRD1
  image: latex_environment
  pull: never
  failure: ignore
  commands:
  - cd doc/srd/
  - latexmk -pdf srd.tex
  depends_on:
  - latex_environment

- name: PRJ1-TST1
  image: latex_environment
  pull: never
  failure: ignore
  commands:
  - cd doc/tst/
  - latexmk -pdf tst.tex
  depends_on:
  - latex_environment

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
