[config]
log_file = "~/.local/timesheeting/timesheeting.log"
db_file = "~/.local/timesheeting/timesheeting.db"
active_log_levels = [ "debug", "error", "info" ]
timezone = "Europe/Paris"
hours_per_workday = 7.7
[keys]
up = "e"
down = "n"
left = "h"
right = "i"
subtabs = "\t"
previous = ","
next = "."
set_now = " "
validate = "\n"
# cancel = "ESCAPE" TODO
duration_display = "d"
entries_screen = "1"
projects_screen = "2"
locations_screen = "3"
project_report_screen = "4"
weekly_report_screen = "5"
add = "a"
rename = "r"
remove = "x"
active_toggle = "b"
active_visibility = "."
task_project_change = "p"
