[db]
file = "~/.local/timesheeting/timesheeting.db"

[time]
timezone = "Europe/Paris"
hours_per_workday = 7.7

[log]
file = "~/.local/timesheeting/timesheeting.log"
active_levels = [ "debug", "error", "info" ]

[keys]
  [keys.navigation]
  up = ["e", "UP"]
  down = ["n", "DOWN"]
  left = ["h", "LEFT"]
  right = ["i", "RIGHT"]
  subtabs = ["TAB"]
  previous = [","]
  next = ["."]
  duration_display = ["d"]
  entries_screen = ["1"]
  projects_screen = ["2"]
  locations_screen = ["3"]
  project_report_screen = ["4"]
  weekly_report_screen = ["5"]
  active_visibility = ["v"]
  quit = ["q"]
  [keys.actions]
  commit_entry = ["ENTER"]
  set_now = ["SPACE"]
  add = ["a"]
  rename = ["r"]
  remove = ["x"]
  active_toggle = ["b"]
  task_project_change = ["p"]
  [keys.edit_mode]
  validate = ["ENTER"]
  cancel = ["ESCAPE"]
  select_suggestion = ["TAB"]
